### PR TITLE
Add disableNormalPass to EffectComposer props

### PR DESCRIPTION
**Pull request by unphased**
For #64 

I'm not sure if `<primitive object={null} />` will trigger anything like more noisy errors. If so we can make it cleaner there. 

For what it's worth, at least to me (a react noob) it feels like the effects should not necessarily be children, and maybe should just be an array as a prop. The decoupling of effect objects from the EffectComposer doesn't help for this scenario!

(I'm still trying to figure out how to properly test at the moment)

### CODE REVIEW

**Comment by talentlessguy** [comment]
Could you test if it works on other effects than SSAO?

**Comment by unphased** [comment]
Yes. I intend to write up a list of cases that I'll test and a list of devices on which they're tested. I'm really gonna be looking to confirm framerate improvements and looking to make sure I did not break any features, demo is useful for this.

**Comment by unphased** [comment]
So far I've found in testing the same scene in the same resolution with the Radeon 560 in my 2017 Macbook Pro: 

- no effectcomposer: 50fps
- With effectcomposer with `multisampling={2}` and a `<Vignette eskil={false} offset={0.1} darkness={0.4} />`: 27fps
- Same as above but also with `disableNormalPass`: 38fps

This is not as much of a benefit as I was expecting but maybe the Vignette isn't as close to zero impact as I thought. It's definitely doing something. Seems like the Stats in my app isn't doing the right kind of math, because I'd rather see the millisecond interval between frames but I just get told 1 to 2 ms from it, which can't be right. Be back later with Spector results

**Comment by talentlessguy** [comment]
@unphased is the PR ready for review or it's still in drafts?

**Comment by unphased** [comment]
It has been working very well, sorry I hadn't had a chance to test it heavily but it definitely should be safe to merge. What do you think you'd like to see for that to happen? 

I've been applying this diff using patch-package in my project.

**Comment by talentlessguy** [comment]
@unphased could you pls pull changes from master first? there are no tests in the repo so don't worry about it

if it works then it works

**Comment by unphased** [comment]
@talentlessguy I merged master cleanly and got this cascade of CI failures. I don't understand the CI check fails. Do you know what they are?

**Comment by talentlessguy** [comment]
@unphased oops that's my fault

I need to configure Vite for prod

will fix asap

**Comment by talentlessguy** [comment]
@unphased pls pull from master again

**Comment by unphased** [comment]
It seems not to have worked

**Comment by talentlessguy** [comment]
oops I accidentally have merged it

**Comment by talentlessguy** [comment]
it works either way, so it's fine

now releasing a new patch version

**Pull request merged**
