### PR TITLE
fix: bundle & transpile n8ao for compat

### LINKED ISSUE #214: N8AO Named export 'Pass' not found
Hi!

I'm trying to use the new `<N8AO />` and running into the following issue:

```javascript
Server Error
SyntaxError: Named export 'Pass' not found. The requested module 'postprocessing' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'postprocessing';
const {Pass: $5Whe3$Pass1} = pkg;

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///Users/shivamsinha/Documents/Design_Work/Portfolio-2023/node_modules/n8ao/dist/N8AO.js (3)
ModuleJob._instantiate
node:internal/modules/esm/module_job (124:21)
async ModuleJob.run
node:internal/modules/esm/module_job (181:5)
async ESMLoader.import
node:internal/modules/esm/loader (281:24)
async importModuleDynamicallyWrapper
node:internal/vm/module (437:15)
```

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
Fixes #214 where `n8ao` is misconfigured to resolve as commonJS with ESM dependencies. I've also transpiled usage of `three/examples/jsm` to `three-stdlib`.

### CODE REVIEW

**Comment by talentlessguy** [comment]
why stop generation of source map? does it cause any bugs?

**Comment by CodyJasonBennett** [comment]
They weren't generated prior, but I'd recommend them for any library. We have `skipLibCheck` on, so I've not opted to also publish source code.

**Comment by talentlessguy** [comment]
@CodyJasonBennett I think it's worth configuring to produce source maps properly in a separate PR

**Comment by CodyJasonBennett** [comment]
I added back sourcemaps in my last commit.

**Pull request merged**
